name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: ${{vars.MONGO_URI}}
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}     
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            nodejs_version: [20]
            os: [ubuntu-latest, ubuntu-22.04]
        
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod   
            ports:
              - 27017:27017
        env:
          MONGO_URI: ${{vars.MONGO_URI_N_P}} 
          MONGO_USERNAME: ${{vars.MONGO_USERNAME_N_P}}
          MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD_N_P}}    
        runs-on: ${{matrix.os}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Cache NPM dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodej-unit-testing-step
          run: npm test

        - name: Archive Test Result
          if: always() 
           # steps.nodej-unit-testing-step.outcome == 'failure' || steps.nodej-unit-testing-step.outcome == 'success'
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
      name: Code Coverage
      container: 
        image: node:20
      services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod   
            options:
              --name mongo 
      env:
          MONGO_URI: mongodb://mongo:27017/superData
          MONGO_USERNAME: ${{vars.MONGO_USERNAME_N_P}}
          MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD_N_P}}    
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        # - name: Setup NodeJS 
        #   uses: actions/setup-node@v4
        #   with:
        #     node-version: 20
        
        - name: Cache NPM dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}

        - name: Install Dependencies
          run: npm install

        - name: Check code coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage_Result
            path: coverage
            retention-days: 5 #  expire in 5 days

    docker:
      permissions: 
        packages: write
      needs: [unit-testing, code-coverage]
      name: Containerizations
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: GHCR Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Build for Testing
          uses:  docker/build-push-action@v6
          with:
            context: .
            push: false
            tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}

        - name: Docker Image Testing
          run: |
            docker images
            docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}
            
            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP
            
            echo Testing Image URL using wget 
            wget -q -O - 127.0.0.1:3000/live | grep live

        - name: Convert repository owner to lowercase
          run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        - name: Container Registry Push
          uses:  docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: | 
              ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
              ghcr.io/${{ env.REPO_OWNER_LOWER }}/solar-system:${{github.sha}}

    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'

        - name: Set Kubeconfig file
          uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{secrets.KUBECONFIG}}

        - name: Fetch Kubernetes Cluster Details
          run: |
            kubectl version 
            echo --------------------------------------------------------
            kubectl get nodes